-- ============================================================
-- Supabase Data Migration Script - Live Situation Monitor
-- Generated by: sql-data-team
-- Date: 2026-02-28
-- ============================================================
--
-- PURPOSE: Populate Supabase database with initial sources and feed items
--
-- PREREQUISITES:
--   1. Base schema must be created first (run supabase-schema.sql)
--   2. This script should be run in Supabase SQL Editor
--   3. Timestamps are in UNIX epoch seconds format
--
-- EXECUTION ORDER:
--   1. Insert sources (creates source_id values)
--   2. Insert feed_items (references source_id)
--   3. Verification queries
--
-- DATA SUMMARY:
--   - 12 News Sources (mainstream, regional, humanitarian, official)
--   - 30 Feed Items (recent headlines from 2026-02-28)
--   - All items include tags, timestamps, and proper foreign keys
--
-- ============================================================

-- ============================================================
-- PART 1: INSERT SOURCES
-- ============================================================
-- Sources are inserted first so feed_items can reference them

INSERT INTO sources (id, name, url, source_type, reliability, language, rate_limit_seconds, is_active, created_at) VALUES
  (1, 'BBC News - Middle East', 'http://feeds.bbci.co.uk/news/world/middle_east/rss.xml', 'mainstream', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (2, 'Reuters - World News', 'https://www.reutersagency.com/feed/?taxonomy=best-topics&post_type=best', 'mainstream', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (3, 'AP News - Middle East', 'https://feedx.net/rss/ap.xml', 'mainstream', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'regional', 4, 'en', 300, true, extract(epoch from now())::bigint),
  (5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'regional', 4, 'en', 300, true, extract(epoch from now())::bigint),
  (6, 'Haaretz', 'https://www.haaretz.com/cmlink/1.628752', 'regional', 4, 'en', 300, true, extract(epoch from now())::bigint),
  (7, 'The Jerusalem Post', 'https://www.jpost.com/rss/rssfeedsheadlines.aspx', 'regional', 4, 'en', 300, true, extract(epoch from now())::bigint),
  (8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'regional', 4, 'en', 300, true, extract(epoch from now())::bigint),
  (9, 'ReliefWeb - Updates', 'https://reliefweb.int/updates/rss.xml', 'humanitarian', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (10, 'UN OCHA - News', 'https://www.unocha.org/rss.xml', 'humanitarian', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (11, 'UN News - Middle East', 'https://news.un.org/feed/subscribe/en/news/region/middle-east/feed/rss.xml', 'official', 5, 'en', 300, true, extract(epoch from now())::bigint),
  (12, 'UN Security Council', 'https://www.un.org/press/en/content/security-council/rss', 'official', 5, 'en', 300, true, extract(epoch from now())::bigint);

-- Reset sequence to continue from 13
SELECT setval('sources_id_seq', 12, true);

-- ============================================================
-- PART 2: INSERT FEED ITEMS
-- ============================================================
-- Feed items reference source_id from above sources
-- 30 recent news items covering military, political, and humanitarian events

INSERT INTO feed_items (
  id, source_id, source_name, source_url, canonical_url,
  published_at, fetched_at, title_original, lang, title_en,
  tags, reliability, is_duplicate, created_at
) VALUES
  (176, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/norway-advises-against-travel-middle-east-states',
   1772307234, 1772307266, 'Norway advises against travel to Middle East states', 'en', 'Norway advises against travel to Middle East states',
   '["Security"]'::jsonb, 4, false, 1772307266),
  (177, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/italys-defence-minister-stranded-dubai-after-strikes',
   1772306684, 1772307266, 'Italy's defence minister stranded in Dubai after strikes', 'en', 'Italy's defence minister stranded in Dubai after strikes',
   '["Politics","Civilian Impact"]'::jsonb, 4, false, 1772307266),
  (175, 3, 'AP News - Middle East', 'https://feedx.net/rss/ap.xml', 'https://apnews.com/article/congress-war-powers-trump-iran-constitution-37ec6685d9ded1d467a719f91e537487',
   1772306581, 1772307265, 'War powers debate intensifies after Trump orders attack on Iran without approval by Congress', 'en', 'War powers debate intensifies after Trump orders attack on Iran without approval by Congress',
   '["Politics","Military","Security","Ceasefire","Diplomacy"]'::jsonb, 5, false, 1772307265),
  (178, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/netanyahu-says-iran-war-continue-long-necessary-claims-khamenei-likely',
   1772306159, 1772307266, 'Netanyahu says Iran war to continue ''as long as necessary'', claims Khamenei likely killed', 'en', 'Netanyahu says Iran war to continue ''as long as necessary'', claims Khamenei likely killed',
   '["Politics","Civilian Impact","Security","Diplomacy","Protests"]'::jsonb, 4, false, 1772307266),
  (173, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/video/newsfeed/2026/2/28/diplomacy-was-betrayed-by-the-americans-iranian-fm-spokesman?traffic_source=rss',
   1772306014, 1772307265, '''Diplomacy was betrayed by the Americans'': Iranian FM spokesman', 'en', '''Diplomacy was betrayed by the Americans'': Iranian FM spokesman',
   '["International"]'::jsonb, 4, false, 1772307265),
  (179, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/turkey-frustrated-after-failing-prevent-us-strike-iran-scrambles-contain',
   1772305082, 1772307266, 'Turkey frustrated after failing to prevent US strike on Iran, scrambles to contain fallout: Analysis', 'en', 'Turkey frustrated after failing to prevent US strike on Iran, scrambles to contain fallout: Analysis',
   '["Security","Politics","Ceasefire","Diplomacy","Refugees"]'::jsonb, 4, false, 1772307266),
  (15, 3, 'AP News - Middle East', 'https://feedx.net/rss/ap.xml', 'https://apnews.com/article/children-immigration-detention-dilley-trump-administration-ice-8ab12c9357ff3b8d400cfa2b2dbe85ed',
   1772304781, 1772305353, 'Worms in food, poor medical care, lights on 24/7: Families tell of life in Texas detention center', 'en', 'Worms in food, poor medical care, lights on 24/7: Families tell of life in Texas detention center',
   '["Politics","Humanitarian","Hostages","Civilian Impact","Security"]'::jsonb, 5, false, 1772305353),
  (174, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/video/newsfeed/2026/2/28/us-and-israel-strike-iran-what-happened?traffic_source=rss',
   1772304635, 1772307265, 'US and Israel strike Iran: what happened?', 'en', 'US and Israel strike Iran: what happened?',
   '["Security"]'::jsonb, 4, false, 1772307265),
  (180, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/israeli-us-attacks-iran-not-permitted-under-un-charter-south-africa',
   1772304426, 1772307266, 'Israeli-US attacks on Iran ''not permitted'' under UN charter: South Africa', 'en', 'Israeli-US attacks on Iran ''not permitted'' under UN charter: South Africa',
   '["International","Security","Politics","Diplomacy","Humanitarian"]'::jsonb, 4, false, 1772307266),
  (181, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/news/dubai-nightmare-iranian-strikes-shatter-calm-uae-business-hub',
   1772304189, 1772307266, '''Dubai''s nightmare'': Iranian strikes shatter calm of UAE business hub', 'en', '''Dubai''s nightmare'': Iranian strikes shatter calm of UAE business hub',
   '["Security","International","Military","Hostages","Politics"]'::jsonb, 4, false, 1772307266),
  (1, 5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://www.timesofisrael.com/american-jewish-groups-throw-support-behind-us-israeli-operation-against-iran/',
   1772303697, 1772305353, 'American Jewish groups throw support behind US-Israeli operation against Iran', 'en', 'American Jewish groups throw support behind US-Israeli operation against Iran',
   '["Security"]'::jsonb, 4, false, 1772305353),
  (182, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/qatar-suspends-public-events-over-security-concerns',
   1772303266, 1772307266, 'Qatar suspends public events over security concerns', 'en', 'Qatar suspends public events over security concerns',
   '["Security","Ceasefire","Politics"]'::jsonb, 4, false, 1772307266),
  (2, 5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://www.timesofisrael.com/before-strikes-trump-was-told-attacking-iran-is-high-risk-high-reward/',
   1772302976, 1772305353, 'Before strikes, Trump was told attacking Iran is high risk, high reward', 'en', 'Before strikes, Trump was told attacking Iran is high risk, high reward',
   '["Politics"]'::jsonb, 4, false, 1772305353),
  (3, 5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://www.timesofisrael.com/hezbollah-condemns-strikes-on-iran-but-stops-short-of-pledging-to-attack-israel/',
   1772302555, 1772305353, 'Hezbollah condemns strikes on Iran but stops short of pledging to attack Israel', 'en', 'Hezbollah condemns strikes on Iran but stops short of pledging to attack Israel',
   '["Security","Military","Diplomacy"]'::jsonb, 4, false, 1772305353),
  (183, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/iran-says-least-200-killed-us-israeli-strikes',
   1772302237, 1772307266, 'Iran says at least 200 killed in US-Israeli strikes', 'en', 'Iran says at least 200 killed in US-Israeli strikes',
   '["Civilian Impact","Humanitarian"]'::jsonb, 4, false, 1772307266),
  (25, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/video/newsfeed/2026/2/28/suspected-iranian-drone-hits-bahrain-high-rise-building?traffic_source=rss',
   1772302228, 1772305353, 'Suspected Iranian drone hits Bahrain high-rise building', 'en', 'Suspected Iranian drone hits Bahrain high-rise building',
   '["International"]'::jsonb, 4, false, 1772305353),
  (184, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/israel-says-200-jets-struck-500-targets-iran',
   1772301503, 1772307266, 'Israel says 200 jets struck 500 targets in Iran', 'en', 'Israel says 200 jets struck 500 targets in Iran',
   '["Military"]'::jsonb, 4, false, 1772307266),
  (4, 5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://toi.li/wxV7in',
   1772301394, 1772305353, 'Send a Purim eCard for the Orphans of Israel''s Fallen Heroes - Sponsored Content', 'en', 'Send a Purim eCard for the Orphans of Israel''s Fallen Heroes - Sponsored Content',
   '["International"]'::jsonb, 4, false, 1772305353),
  (185, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/erdogan-condemns-attacks-iran-urges-de-escalation',
   1772301161, 1772307266, 'Erdogan condemns attacks on Iran, urges de-escalation', 'en', 'Erdogan condemns attacks on Iran, urges de-escalation',
   '["Ceasefire"]'::jsonb, 4, false, 1772307266),
  (26, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/editorial/2026/2/28/nine-months-after-12-day-war-us-israel-seek-to-topple-irans-leaders?traffic_source=rss',
   1772300677, 1772305353, 'Nine months after 12-day war, US, Israel seek to topple Iran''s leaders', 'en', 'Nine months after 12-day war, US, Israel seek to topple Iran''s leaders',
   '["International"]'::jsonb, 4, false, 1772305353),
  (27, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/sports/2026/2/28/pakistan-edge-last-ball-thriller-against-sri-lanka-but-exit-t20-world-cup?traffic_source=rss',
   1772300549, 1772305353, 'Pakistan edge last-ball thriller against Sri Lanka but exit T20 World Cup', 'en', 'Pakistan edge last-ball thriller against Sri Lanka but exit T20 World Cup',
   '["International"]'::jsonb, 4, false, 1772305353),
  (186, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/israeli-minister-invokes-genocidal-amalek-call-amid-war-iran',
   1772300479, 1772307266, 'Israeli minister invokes genocidal ''Amalek'' call amid war on Iran', 'en', 'Israeli minister invokes genocidal ''Amalek'' call amid war on Iran',
   '["Politics","Security"]'::jsonb, 4, false, 1772307266),
  (5, 5, 'Times of Israel', 'https://www.timesofisrael.com/feed/', 'https://www.timesofisrael.com/backing-us-and-israel-zelensky-says-hoping-for-fall-of-terrorist-regime-in-tehran/',
   1772300462, 1772305353, 'Backing US and Israel, Zelensky says hoping for fall of ''terrorist regime'' in Tehran', 'en', 'Backing US and Israel, Zelensky says hoping for fall of ''terrorist regime'' in Tehran',
   '["Security"]'::jsonb, 4, false, 1772305353),
  (187, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/no-war-iranian-opposition-abroad-pushes-back-against-us-israeli-strikes',
   1772300219, 1772307266, '''No to War'': Iranian opposition abroad pushes back against US-Israeli strikes', 'en', '''No to War'': Iranian opposition abroad pushes back against US-Israeli strikes',
   '["Refugees","Military"]'::jsonb, 4, false, 1772307266),
  (50, 1, 'BBC News - Middle East', 'http://feeds.bbci.co.uk/news/world/middle_east/rss.xml', 'https://www.bbc.com/news/articles/cx2dyz6p3weo?at_medium=RSS&at_campaign=rss',
   1772299946, 1772305353, 'What we know so far: Supreme Leader''s compound hit and Iran''s retaliatory strikes', 'en', 'What we know so far: Supreme Leader''s compound hit and Iran''s retaliatory strikes',
   '["International"]'::jsonb, 5, false, 1772305353),
  (28, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/sports/2026/2/28/lamine-yamal-hits-hat-trick-as-barcelona-beat-villarreal-4-1-in-la-liga?traffic_source=rss',
   1772299892, 1772305353, 'Lamine Yamal hits hat-trick as Barcelona beat Villarreal 4-1 in La Liga', 'en', 'Lamine Yamal hits hat-trick as Barcelona beat Villarreal 4-1 in La Liga',
   '["International"]'::jsonb, 4, false, 1772305353),
  (188, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/news/dubai-nightmare-iranian-strikes-shatter-calm-uae-business-hub',
   1772299712, 1772307266, 'Blasts hit Dubai and Abu Dhabi as UAE sucked into US-Israel conflict with Iran', 'en', 'Blasts hit Dubai and Abu Dhabi as UAE sucked into US-Israel conflict with Iran',
   '["Security","Civilian Impact","Military","Humanitarian","International"]'::jsonb, 4, false, 1772307266),
  (189, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/iranian-drone-hits-high-rise-building-bahrain-no-casualties-reported',
   1772299420, 1772307266, 'An Iranian drone hits a high-rise building in Bahrain, no casualties reported', 'en', 'An Iranian drone hits a high-rise building in Bahrain, no casualties reported',
   '["Humanitarian"]'::jsonb, 4, false, 1772307266),
  (29, 4, 'Al Jazeera - English', 'https://www.aljazeera.com/xml/rss/all.xml', 'https://www.aljazeera.com/video/newsfeed/2026/2/28/scattered-fires-damage-seen-across-israel-as-iran-retaliates?traffic_source=rss',
   1772298975, 1772305353, 'Scattered fires, damage seen across Israel as Iran retaliates', 'en', 'Scattered fires, damage seen across Israel as Iran retaliates',
   '["International"]'::jsonb, 4, false, 1772305353),
  (190, 8, 'Middle East Eye', 'https://www.middleeasteye.net/rss', 'https://www.middleeasteye.net/live-blog/live-blog-update/israel-says-89-lightly-wounded-start-iran-war',
   1772298615, 1772307266, 'Israel says 89 lightly wounded since start of Iran war', 'en', 'Israel says 89 lightly wounded since start of Iran war',
   '["Humanitarian"]'::jsonb, 4, false, 1772307266);

-- Reset sequence to continue after last ID
SELECT setval('feed_items_id_seq', (SELECT MAX(id) FROM feed_items), true);

-- ============================================================
-- PART 3: VERIFICATION QUERIES
-- ============================================================
-- Run these to verify the migration was successful

-- Count total sources
SELECT 'Total Sources:' as metric, COUNT(*) as count FROM sources;

-- Count total feed items
SELECT 'Total Feed Items:' as metric, COUNT(*) as count FROM feed_items;

-- Count feed items per source
SELECT
  s.name as source_name,
  COUNT(f.id) as item_count
FROM sources s
LEFT JOIN feed_items f ON s.id = f.source_id
GROUP BY s.id, s.name
ORDER BY item_count DESC;

-- Check for any orphaned feed_items (should be 0)
SELECT COUNT(*) as orphaned_items
FROM feed_items f
WHERE NOT EXISTS (SELECT 1 FROM sources s WHERE s.id = f.source_id);

-- Show recent feed items
SELECT
  f.id,
  f.source_name,
  f.title_original,
  f.published_at,
  to_timestamp(f.published_at) as published_date
FROM feed_items f
ORDER BY f.published_at DESC
LIMIT 10;

-- Verify tag structure (should show JSON arrays)
SELECT
  f.id,
  f.title_original,
  f.tags
FROM feed_items f
WHERE f.tags IS NOT NULL
LIMIT 5;

-- ============================================================
-- MIGRATION COMPLETE
-- ============================================================
-- Next steps:
--   1. Run scenario migration script (002_scenario_analysis.sql)
--   2. Configure ingestion cron jobs
--   3. Test API endpoints
-- ============================================================
