-- ============================================================
-- Supabase Migration Script - Live Situation Monitor
-- Generated by sql-data-team
-- Date: 2026-02-28
-- ============================================================
--
-- PURPOSE: Populate Supabase database with initial sources and feed items
--
-- PREREQUISITES:
--   1. Base schema must be created first (run supabase-schema.sql)
--   2. This script should be run in Supabase SQL Editor
--   3. Timestamps are in UNIX epoch seconds format
--
-- EXECUTION ORDER:
--   1. Insert sources (creates source_id values)
--   2. Insert feed_items (references source_id)
--   3. Verification queries
--
-- ============================================================

-- ============================================================
-- PART 1: INSERT SOURCES
-- ============================================================
-- Sources are inserted first so feed_items can reference them

-- [SOURCES INSERT STATEMENTS WILL GO HERE]
-- Waiting for sources-creator agent to complete...

-- ============================================================
-- PART 2: INSERT FEED ITEMS
-- ============================================================
-- Feed items reference source_id from above sources

-- [FEED_ITEMS INSERT STATEMENTS WILL GO HERE]
-- Waiting for feed-items-creator agent to complete...

-- ============================================================
-- PART 3: VERIFICATION QUERIES
-- ============================================================
-- Run these to verify the migration was successful

-- Count total sources
SELECT 'Total Sources:' as metric, COUNT(*) as count FROM sources;

-- Count total feed items
SELECT 'Total Feed Items:' as metric, COUNT(*) as count FROM feed_items;

-- Count feed items per source
SELECT
  s.name as source_name,
  COUNT(f.id) as item_count
FROM sources s
LEFT JOIN feed_items f ON s.id = f.source_id
GROUP BY s.id, s.name
ORDER BY item_count DESC;

-- Check for any orphaned feed_items (should be 0)
SELECT COUNT(*) as orphaned_items
FROM feed_items f
WHERE NOT EXISTS (SELECT 1 FROM sources s WHERE s.id = f.source_id);

-- Show recent feed items
SELECT
  f.id,
  f.source_name,
  f.title_original,
  f.published_at,
  to_timestamp(f.published_at) as published_date
FROM feed_items f
ORDER BY f.published_at DESC
LIMIT 10;

-- ============================================================
-- END OF MIGRATION SCRIPT
-- ============================================================
